# Site settings
author: Nicholas van Zuiden-Rylander
title: Nick's Beginner Code Blog
header-img: img/home-bg.png
email: nick.rylander@outlook.com
copyright_name: Nicholas van Zuiden-Rylander
description: > # this means to ignore newlines until "baseurl:"
  From Beginner to Pro
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  NickRylander

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
